#!/usr/bin/env bash
# ============================================================
#  Letters & Numbers — deploy audio voice-pack
#
#  Separate from scripts/deploy.sh because:
#    - audio/ is gitignored (too large/personal to track in git)
#    - voice packs are regenerated infrequently
#    - regular deploys should never wipe an existing voice pack
#
#  Usage:
#    bash scripts/deploy-audio.sh
#
#  Prerequisites:
#    - audio/ folder generated by `python scripts/generate-voices.py`
#    - One-time droplet setup already done (lnum-deploy + /opt/apps/...)
# ============================================================
set -euo pipefail

HOST="${HOST:-deploy@192.241.132.219}"
REMOTE_DIR="${REMOTE_DIR:-/opt/apps/letters-and-numbers}"
TENANT_USER="${TENANT_USER:-lnum-deploy}"
STAGING="${STAGING:-/tmp/lnum-audio-staging}"
DOMAIN="${DOMAIN:-letters.guardcybersolutionsllc.com}"

if [[ ! -d "audio" ]]; then
  echo "ERROR: no audio/ folder. Run 'python scripts/generate-voices.py' first." >&2
  exit 1
fi

COUNT=$(find audio -name "*.mp3" 2>/dev/null | wc -l | tr -d ' ')
echo "==========================================================="
echo "  Deploy audio pack — ${COUNT} MP3 files"
echo "  ${HOST}:${REMOTE_DIR}/audio/"
echo "==========================================================="

# Stage
echo "→ Staging audio to ${HOST}:${STAGING}"
ssh "${HOST}" "mkdir -p '${STAGING}'"
rsync -avz --delete audio/ "${HOST}:${STAGING}/audio/"

# Move into place + permissions + reload (Caddy doesn't need reload for
# new files, but doing it is cheap and ensures cache headers are fresh).
echo "→ Installing into ${REMOTE_DIR}/audio/"
ssh "${HOST}" "set -e
  sudo mkdir -p '${REMOTE_DIR}/audio'
  sudo rsync -a --delete '${STAGING}/audio/' '${REMOTE_DIR}/audio/'
  sudo chown -R '${TENANT_USER}:${TENANT_USER}' '${REMOTE_DIR}/audio'
  sudo find '${REMOTE_DIR}/audio' -type f -exec chmod 644 {} \;
  sudo find '${REMOTE_DIR}/audio' -type d -exec chmod 755 {} \;
  rm -rf '${STAGING}'
"

# Smoke-test a couple of paths
echo "→ Smoke-testing audio URLs"
for path in /audio/letters/name/A.mp3 /audio/letters/sound/A.mp3 /audio/letters/word/A.mp3 /audio/numbers/5.mp3; do
  CODE=$(curl -sk -o /dev/null -w "%{http_code}" "https://${DOMAIN}${path}" 2>/dev/null || echo "000")
  printf "  %-40s %s\n" "${path}" "${CODE}"
done

echo "==========================================================="
echo "  ✓ Voice pack deployed."
echo "  Open the app, Settings -> Custom audio files -> Use if present"
echo "==========================================================="
